{% set name = "eelbrain" %}
{% set version = "0.35" %}
{% set sha256 = "aab9f4a1b6cb8aacc877ef06db6b6dd5a74a313fd625463614bd7a21fb9a5bfd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  osx_is_app: true
  skip: true  # [py<38]
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools >=17
  host:
    - libblas
    - libcblas
    - python
    - python.app  # [osx]
    - pywin32-ctypes  # [win]
    - pip
    - cython >=0.21
    - numpy >=1.20
  run:
    - python
    - python.app  # [osx]
    - colormath >=2.1
    - ipython
    - keyring >=5
    - matplotlib-base >=3.3.4
    - mne >=0.19
    - nibabel >=2.5
    - olefile  # [linux]
    - {{ pin_compatible('numpy', lower_bound='1.20') }}
    - pillow
    - pysurfer >=0.9
    - nilearn
    - packaging
    - scipy >=1.5
    - numba
    - tqdm >=4.40
    - wxpython >=4.0.3, !=4.1.0
    - mayavi >=4.6.2
    - pyface !=7.2.0  # broken for wx

test:
  imports:
    - eelbrain
    - eelbrain.load
    - eelbrain.mne_fixes
    - eelbrain.plot
    - eelbrain.save

about:
  home: http://eelbrain.readthedocs.io
  summary: MEG/EEG analysis tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: http://eelbrain.readthedocs.io/
  dev_url: https://github.com/christianbrodbeck/eelbrain

extra:
  recipe-maintainers:
    - christianbrodbeck
