{% set name = "eelbrain" %}
{% set version = "0.33.1" %}
{% set sha256 = "a8b920f8db4c5331807107f81fb408e475280076c3a435830bf076b41f5f363c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  osx_is_app: true
  skip: true  # [py<37]
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools >=17
  host:
    - libblas
    - libcblas
    - python
    - python.app  # [osx]
    - olefile  # [win or linux]
    - pywin32-ctypes  # [win]
    - pip
    - cython >=0.21
    - numpy
  run:
    - python
    - python.app  # [osx]
    - colormath >=2.1
    - ipython
    - keyring >=5
    - matplotlib-base >=3
    - mne >=0.17
    - nibabel >=2.5
    - olefile  # [linux]
    - {{ pin_compatible('numpy') }}
    - pillow
    - pysurfer >=0.9
    - nilearn
    - packaging
    - scipy >=1.3
    - numba
    - tqdm >=4.19
    - wxpython >=4.0.3
    - mayavi >=4.6.2

test:
  imports:
    - eelbrain
    - eelbrain.load
    - eelbrain.mne_fixes
    - eelbrain.plot
    - eelbrain.save

about:
  home: http://eelbrain.readthedocs.io
  summary: MEG/EEG analysis tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: http://eelbrain.readthedocs.io/
  dev_url: https://github.com/christianbrodbeck/eelbrain

extra:
  recipe-maintainers:
    - christianbrodbeck
